### PR TITLE
Let the code be compiled in melodic

### PR DESCRIPTION
**Pull request by gachiemchiep**

### CODE REVIEW

**Comment by miguelriemoliveira** [comment]
@joao-pm-santos96 do you think we should merge this? Can you take a look?

**Comment by joao-pm-santos96** [comment]
@gachiemchiep back in the day, I had no issues compiling the master branch on melodic. Can you please give us further details?

@miguelriemoliveira the changes are minor, for me it's ok, but I did not try to compile it

**Comment by gachiemchiep** [comment]
When i compiled in the master branch, the error looks like this. 
It's just a minor change that change from using boost::shared_ptr into pcl's pointer format ::Ptr. 

```bash
Errors     << point_cloud_spatial_filter:make /home/jil/workspace/catkin_ws_test/logs/point_cloud_spatial_filter/build.make.000.log                                                                                                   
In file included from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/src/point_cloud_spatial_filter.cpp:4:0:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h: In member function ‘void PerceptionPreprocessing::pointCloudCallback(const PointCloud2Ptr&)’:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h:496:54: error: no matching function for call to ‘pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >&)’
             ConditionalRemoval<T> condrem(_range_cond);
                                                      ^
In file included from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h:28:0,
                 from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/src/point_cloud_spatial_filter.cpp:4:
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:614:7: note: candidate: pcl::ConditionalRemoval<PointT>::ConditionalRemoval(int) [with PointT = pcl::PointXYZRGB]
       ConditionalRemoval (int extract_removed_indices = false) :
       ^~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:614:7: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘int’
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note: candidate: pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(const pcl::ConditionalRemoval<pcl::PointXYZRGB>&)
   class ConditionalRemoval : public Filter<PointT>
         ^~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘const pcl::ConditionalRemoval<pcl::PointXYZRGB>&’
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note: candidate: pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(pcl::ConditionalRemoval<pcl::PointXYZRGB>&&)
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘pcl::ConditionalRemoval<pcl::PointXYZRGB>&&’
In file included from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/src/point_cloud_spatial_filter_node.cpp:7:0:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h: In member function ‘void PerceptionPreprocessing::pointCloudCallback(const PointCloud2Ptr&)’:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h:496:54: error: no matching function for call to ‘pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >&)’
             ConditionalRemoval<T> condrem(_range_cond);
                                                      ^
In file included from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h:28:0,
                 from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/src/point_cloud_spatial_filter_node.cpp:7:
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:614:7: note: candidate: pcl::ConditionalRemoval<PointT>::ConditionalRemoval(int) [with PointT = pcl::PointXYZRGB]
       ConditionalRemoval (int extract_removed_indices = false) :
       ^~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:614:7: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘int’
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note: candidate: pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(const pcl::ConditionalRemoval<pcl::PointXYZRGB>&)
   class ConditionalRemoval : public Filter<PointT>
         ^~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘const pcl::ConditionalRemoval<pcl::PointXYZRGB>&’
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note: candidate: pcl::ConditionalRemoval<pcl::PointXYZRGB>::ConditionalRemoval(pcl::ConditionalRemoval<pcl::PointXYZRGB>&&)
/usr/local/include/pcl-1.10/pcl/filters/conditional_removal.h:590:9: note:   no known conversion for argument 1 from ‘boost::shared_ptr<pcl::ConditionAnd<pcl::PointXYZRGB> >’ to ‘pcl::ConditionalRemoval<pcl::PointXYZRGB>&&’
make[2]: *** [CMakeFiles/point_cloud_spatial_filter.dir/src/point_cloud_spatial_filter.cpp.o] Error 1
make[1]: *** [CMakeFiles/point_cloud_spatial_filter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/src/point_cloud_spatial_filter_node.cpp:7:0:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h: In member function ‘void PerceptionPreprocessing::processFeedback(const InteractiveMarkerFeedbackConstPtr&)’:
/home/jil/workspace/catkin_ws_test/src/octomap_tools/point_cloud_spatial_filter/include/point_cloud_spatial_filter/point_cloud_spatial_filter.h:440:31: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                         system(cmd.c_str());
                         ~~~~~~^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/point_cloud_spatial_filter_node.dir/src/point_cloud_spatial_filter_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/point_cloud_spatial_filter_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/jil/workspace/catkin_ws_test/build/point_cloud_spatial_filter; catkin build --get-env point_cloud_spatial_filter | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
......................................................................................................................................................................................................................................
Failed     << point_cloud_spatial_filter:make              [ Exited with code 2 ]                                                                                                                                                     
Failed    <<< point_cloud_spatial_filter                   [ 14.5 seconds ]                                                                                                                                                           
Abandoned <<< interactive_region_definition                [ Unrelated job failed ]                                                                                                                                                   
Finished  <<< world_model_consistency_check                [ 37.5 seconds ]                                                                                                                                                           
[build] Summary: 3 of 5 packages succeeded.                                                                                                                                                                                           
[build]   Ignored:   None.                                                                                                                                                                                                            
[build]   Warnings:  2 packages succeeded with warnings.                                                                                                                                                                              
[build]   Abandoned: 1 packages were abandoned.                                                                                                                                                                                       
[build]   Failed:    1 packages failed.                                                                                                                                                                                               
[build] Runtime: 46.6 seconds total.                                                                                                                                                                                                  
[build] Note: Workspace packages have changed, please re-source setup files to use them.

```

**Comment by joao-pm-santos96** [comment]
Must be some change made on pcl or some other package... seams ok then

**Comment by miguelriemoliveira** [comment]
Alright. Thanks to both. I will merge.

**Pull request merged**
